version: '3.8'

services:
  # Full Stack Trading App (Frontend + Backend)
  trading-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8314:2314"
    environment:
      - HONO_PORT=2314
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2314/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge