version: '3.8'

services:
  # Trading Backend Service (Hono/Node.js)
  backend:
    build:
      context: .
      dockerfile: hono-backend/Dockerfile
    ports:
      - "2314:2314"
    environment:
      - NODE_ENV=production
      - HONO_PORT=2314
      - NODE_ENV=production
    volumes:
      - ./hono-backend/src:/app/src:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2314"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    networks:
      - trading-network

  # Frontend Service (React/Vite)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "2414:2414"
    environment:
      - NODE_ENV=production
      - VITE_WS_URL=ws://localhost:2314/ws
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend/src:/app/src:ro
    restart: unless-stopped
    networks:
      - trading-network

  # Redis (Optional - for caching and session management)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - trading-network

  # Nginx (Optional - for reverse proxy)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - trading-network

volumes:
  redis_data:

networks:
  trading-network:
    driver: bridge